# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Mandatory: Enables AndroidX support across all modules and dependencies
android.useAndroidX=true

# Enables namespacing for each library's R class to reduce APK/AAR size
android.nonTransitiveRClass=true

# Kotlin code style
kotlin.code.style=official